export const FETCH_TRIP_DETAILS_REQUEST = 'FETCH_TRIP_DETAILS_REQUEST';
export const FETCH_TRIP_DETAILS_REQUEST_SUCCESS = 'FETCH_TRIP_DETAILS_REQUEST_SUCCESS';
export const FETCH_TRIP_DETAILS_REQUEST_FAILURE = 'FETCH_TRIP_DETAILS_REQUEST_FAILURE';

export const SELECT_FROM_VALUE_CHANGED = 'SELECT_FROM_VALUE_CHANGED';
export const SELECT_TO_VALUE_CHANGED = 'SELECT_TO_VALUE_CHANGED';

export const OPTION_CHANGED = 'OPTION_CHANGED';

export const RESET_ALL_VALUES = 'RESET_ALL_VALUES';